# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
pool:
  vmImage: 'ubuntu-latest'
stages:
- stage: Build
  jobs:
  - job: Build

    steps:
    - script: echo Hello, world!
      displayName: 'Run a one-line script'

    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
      displayName: 'Run a multi-line script'
#    - powershell: start-sleep -seconds 600
#      displayName: take a nap

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
- stage: Larry
  dependsOn: Build
  jobs:
  - deployment: Larry1
    environment: Dev
    strategy:
      runOnce:
        deploy:
          steps:
            - powershell: |
                write-host "Hello, World from an ENV deployment"
- stage: Moe
  dependsOn: Build
  jobs:
  - deployment: Moe2
    environment: Stage
    strategy:
      runOnce:
        deploy:
          steps:
            - powershell: |
                write-host "Hello, World from an ENV deployment"
            - powershell: start-sleep -seconds 600
              displayName: take a nap

- stage: Curly
  dependsOn: Build
  jobs:
  - deployment: Curly3
    environment: Prod
    strategy:
      runOnce:
        deploy:
          steps:
            - powershell: |
                write-host "Hello, World from an ENV deployment"
            - powershell: |
                throw "testing failure"
